<?php

declare(strict_types=1);

namespace App\Mail;

use App\Models\Booking;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * Post-training email asking the shooter to leave a short testimonial via a
 * signed URL. The URL is generated by the Filament invite action so it can
 * embed the recipient's name and the discipline/event context.
 */
class TestimonialInvitation extends Mailable implements ShouldQueue
{
    use Queueable;
    use SerializesModels;

    public function __construct(
        public Booking $booking,
        public string $signedUrl,
    ) {}

    public function envelope(): Envelope
    {
        $title = $this->booking->trainingEvent?->displayTitle() ?? 'your training day';

        return new Envelope(subject: 'How was '.$title.'? Leave a quick review');
    }

    public function content(): Content
    {
        return new Content(
            markdown: 'emails.testimonial-invitation',
            with: [
                'booking' => $this->booking,
                'signedUrl' => $this->signedUrl,
                'event' => $this->booking->trainingEvent,
            ],
        );
    }
}
